//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WideWorldImporters.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Cities = new HashSet<City>();
            this.Countries = new HashSet<Country>();
            this.DeliveryMethods = new HashSet<DeliveryMethod>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.People1 = new HashSet<Person>();
            this.StateProvinces = new HashSet<StateProvince>();
            this.SystemParameters = new HashSet<SystemParameter>();
            this.TransactionTypes = new HashSet<TransactionType>();
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.SupplierCategories = new HashSet<SupplierCategory>();
            this.Suppliers = new HashSet<Supplier>();
            this.Suppliers1 = new HashSet<Supplier>();
            this.Suppliers2 = new HashSet<Supplier>();
            this.SupplierTransactions = new HashSet<SupplierTransaction>();
            this.BuyingGroups = new HashSet<BuyingGroup>();
            this.CustomerCategories = new HashSet<CustomerCategory>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Customers2 = new HashSet<Customer>();
            this.CustomerTransactions = new HashSet<CustomerTransaction>();
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Invoices2 = new HashSet<Invoice>();
            this.Invoices3 = new HashSet<Invoice>();
            this.Invoices4 = new HashSet<Invoice>();
            this.OrderLines = new HashSet<OrderLine>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
            this.Orders3 = new HashSet<Order>();
            this.SpecialDeals = new HashSet<SpecialDeal>();
            this.Colors = new HashSet<Color>();
            this.PackageTypes = new HashSet<PackageType>();
            this.StockGroups = new HashSet<StockGroup>();
            this.StockItemHoldings = new HashSet<StockItemHolding>();
            this.StockItems = new HashSet<StockItem>();
            this.StockItemStockGroups = new HashSet<StockItemStockGroup>();
            this.StockItemTransactions = new HashSet<StockItemTransaction>();
        }
    
        public int PersonID { get; set; }
        public string FullName { get; set; }
        public string PreferredName { get; set; }
        public string SearchName { get; set; }
        public bool IsPermittedToLogon { get; set; }
        public string LogonName { get; set; }
        public bool IsExternalLogonProvider { get; set; }
        public byte[] HashedPassword { get; set; }
        public bool IsSystemUser { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsSalesperson { get; set; }
        public string UserPreferences { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public byte[] Photo { get; set; }
        public string CustomFields { get; set; }
        public string OtherLanguages { get; set; }
        public int LastEditedBy { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<DeliveryMethod> DeliveryMethods { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<Person> People1 { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
        public virtual ICollection<SystemParameter> SystemParameters { get; set; }
        public virtual ICollection<TransactionType> TransactionTypes { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Supplier> Suppliers1 { get; set; }
        public virtual ICollection<Supplier> Suppliers2 { get; set; }
        public virtual ICollection<SupplierTransaction> SupplierTransactions { get; set; }
        public virtual ICollection<BuyingGroup> BuyingGroups { get; set; }
        public virtual ICollection<CustomerCategory> CustomerCategories { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<Customer> Customers2 { get; set; }
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        public virtual ICollection<Invoice> Invoices2 { get; set; }
        public virtual ICollection<Invoice> Invoices3 { get; set; }
        public virtual ICollection<Invoice> Invoices4 { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Order> Orders2 { get; set; }
        public virtual ICollection<Order> Orders3 { get; set; }
        public virtual ICollection<SpecialDeal> SpecialDeals { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<PackageType> PackageTypes { get; set; }
        public virtual ICollection<StockGroup> StockGroups { get; set; }
        public virtual ICollection<StockItemHolding> StockItemHoldings { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
        public virtual ICollection<StockItemStockGroup> StockItemStockGroups { get; set; }
        public virtual ICollection<StockItemTransaction> StockItemTransactions { get; set; }
    }
}
