apiVersion: v1
kind: ConfigMap
metadata:
  name: wwi-api-config-override
  namespace: wwi
data:
  override.json: |-
    {
      "Caching": {
        "Enabled": true,
        "MemoryCache": {
          "DurationSeconds": 180
        }
      }
    }