apiVersion: v1
kind: Secret
metadata:
  name: wwi-api-secret-connectionstrings
  namespace: wwi
type: Opaque
stringData:
  connectionstrings.json: |
    {
      "ConnectionStrings": {
        "wwi-db": "Server=wwi-db.wwi.svc.cluster.local;Database=WideWorldImporters;User Id=sa;Password=w1d3_PR*dd;"
      }
    }