apiVersion: v1
kind: ConfigMap
metadata:
  name: wwi-config-logging
  namespace: wwi
data:
  logging.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Warning"
        }
      }
    }