apiVersion: v1
kind: Secret
metadata:
  name: wwi-svc-connectionstrings
  namespace: wwi
type: Opaque
stringData:
  connectionStrings.config: |-
    <connectionStrings>
      <add name="WideWorldImportersEntities" connectionString="metadata=res://*/WideWorldImportersModel.csdl|res://*/WideWorldImportersModel.ssdl|res://*/WideWorldImportersModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=wwi-db.wwi.svc.cluster.local;initial catalog=WideWorldImporters;persist security info=True;user id=sa;password=w1d3_PR*dd;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
    </connectionStrings>